[font]
size = 16.0

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.4
decorations = "Buttonless"
blur = true
startup_mode = "Maximized"
dimensions = { columns = 150, lines = 42 }
position = { x = 550, y = 250 }
